CREATE TABLE Person(
 id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 firstName VARCHAR(30) NOT NULL,
 middleName VARCHAR(30) NOT NULL,
 lastName VARCHAR(30) NOT NULL,
 birthdayYear int NOT NULL CHECK (birthdayYear > 1900),
 CONSTRAINT person_name_key UNIQUE(firstName, middleName, lastName)
);


CREATE TABLE Book(
 id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 person_id int REFERENCES Person(id) ON DELETE SET NULL,
 title VARCHAR(50) NOT NULL UNIQUE,
 author VARCHAR(50) NOT NULL,
 year int CHECK (year > 1500)
);

